[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<*>
lib_deps =
    WiFi
    WiFiClientSecure
    8lall0/Minitel1B_Hard@^1.0.0
    links2004/WebSockets@^2.7.3
    ewpa/LibSSH-ESP32@^5.8.0
    bblanchon/ArduinoJson@^7.4.3
